app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: api

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type: annotation
    prefix: admin