app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /api

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type: annotation
    prefix: admin

