AppBundle\Entity\Aficion:
    type: entity
    table: aficion
    indexes:
        AFICION_CATEGORIA_IDX:
            columns:
                - categoria_id
    uniqueConstraints:
        AFICION_NAME_UNIQ:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    manyToOne:
        categoria:
            targetEntity: Categoria
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
