AppBundle\Entity\Comentario:
    type: entity
    table: comentario
    indexes:
        COMENTARIO_EVENTO_IDX:
            columns:
                - evento_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        subject:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
    manyToOne:
        evento:
            targetEntity: Evento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                evento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
