AppBundle\Entity\Documento:
    type: entity
    table: documento
    indexes:
        TIPO_DOCUMENTO_IDX:
            columns:
                - tipo_documento_id
        DOCUMENTO_USUARIO_IDX:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        path:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        createdAt:
            type: date
            nullable: false
            column: created_at
        description:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    manyToOne:
        tipoDocumento:
            targetEntity: TipoDocumento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_documento_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
