AppBundle\Entity\EventoCategoria:
    type: entity
    table: evento_categoria
    indexes:
        EC_EVENTO_IDX:
            columns:
                - evento_id
        EC_CATEGORIA_IDX:
            columns:
                - categoria_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        categoria:
            targetEntity: Categoria
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
        evento:
            targetEntity: Evento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                evento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
