AppBundle\Entity\Rol:
    type: entity
    table: rol
    uniqueConstraints:
        ROL_NAME_UNIQUE:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
