AppBundle\Entity\TipoLugar:
    type: entity
    table: tipo_lugar
    uniqueConstraints:
        LUGAR_NAME_UNIQUE:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
