AppBundle\Entity\UsuarioRol:
    type: entity
    table: usuario_rol
    indexes:
        UR_USUARIO_IDX:
            columns:
                - usuario_id
        UR_ROL_IDX:
            columns:
                - rol_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        rol:
            targetEntity: Rol
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
