AppBundle\Entity\UsuarioEvento:
    type: entity
    table: usuario_evento
    indexes:
        UE_USUARIO_IDX:
            columns:
                - usuario_id
        UE_EVENTO_IDX:
            columns:
                - evento_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        isOwner:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: 'no'
            column: is_owner
        declined:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: 'no'
    manyToOne:
        evento:
            targetEntity: Evento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                evento_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
